### Numpy practice
The Numpy library is the core library for scientific computing in Python. It provides a high-performance multidimentional array object, and tools for working with these arrays.


In [3]:
import numpy as np

### create arrays by using list

In [8]:
a = np.array([1,2,3])
a

array([1, 2, 3])

In [11]:
b = np.array([[1,2,3],[4,5,6]])
b

array([[1, 2, 3],
       [4, 5, 6]])

In [13]:
c = np.array([[[1,2],[2,3]],[[3,4],[4,5]]])
c

array([[[1, 2],
        [2, 3]],

       [[3, 4],
        [4, 5]]])

### creat palceholder

In [15]:
np.zeros([3,4])

array([[ 0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.]])

In [16]:
np.ones([2,3,4])

array([[[ 1.,  1.,  1.,  1.],
        [ 1.,  1.,  1.,  1.],
        [ 1.,  1.,  1.,  1.]],

       [[ 1.,  1.,  1.,  1.],
        [ 1.,  1.,  1.,  1.],
        [ 1.,  1.,  1.,  1.]]])

In [37]:
a = np.arange(10, 35, 5) # 5 is the interval
b = np.linspace(10, 35, 5) # 5 is number of equal spaced dots
c = np.linspace(10, 35, (35-10)//5+1) # 5 is the interval
print(a)
print(b)
print(c)

[10 15 20 25 30]
[ 10.    16.25  22.5   28.75  35.  ]
[ 10.  15.  20.  25.  30.  35.]


### inspecting the array

In [48]:
# generate random matrix, compared with ones and zeros commands
m = np.random.randn(2,3,4)
m

array([[[-0.35427059, -0.95110854,  1.04185567,  0.47116457],
        [ 1.02677365, -0.08758251, -0.23187042,  1.174793  ],
        [ 1.01150871, -0.29200624,  0.79593575, -1.30430787]],

       [[-0.64798385, -0.93424273, -0.74650915,  0.69231104],
        [ 1.06701099, -0.7997573 ,  1.0744899 , -0.24733323],
        [-1.92536334,  0.59671385,  0.47175326,  1.47532876]]])

In [49]:
m.shape

(2, 3, 4)

In [50]:
len(m) # number of element in the most outer layer

2

In [52]:
m.ndim # number of element in the second layer

3

In [53]:
m.size # number of all fundamental elements (2*3*4)

24

In [55]:
m.astype(int) # convert type as-type

array([[[ 0,  0,  1,  0],
        [ 1,  0,  0,  1],
        [ 1,  0,  0, -1]],

       [[ 0,  0,  0,  0],
        [ 1,  0,  1,  0],
        [-1,  0,  0,  1]]])

### array mathematics

In [60]:
a = np.ones([3,4])
b = np.ones([3,4])
print(a)
print(b)

[[ 1.  1.  1.  1.]
 [ 1.  1.  1.  1.]
 [ 1.  1.  1.  1.]]
[[ 1.  1.  1.  1.]
 [ 1.  1.  1.  1.]
 [ 1.  1.  1.  1.]]


In [61]:
a - b # elementwise

array([[ 0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.]])

In [62]:
a + b # elementwise

array([[ 2.,  2.,  2.,  2.],
       [ 2.,  2.,  2.,  2.],
       [ 2.,  2.,  2.,  2.]])

In [64]:
a / b # elementwise

array([[ 1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.]])

In [65]:
(a + b) * (a + b) # elementwise

array([[ 4.,  4.,  4.,  4.],
       [ 4.,  4.,  4.,  4.],
       [ 4.,  4.,  4.,  4.]])

In [68]:
np.exp(a)

array([[ 2.71828183,  2.71828183,  2.71828183,  2.71828183],
       [ 2.71828183,  2.71828183,  2.71828183,  2.71828183],
       [ 2.71828183,  2.71828183,  2.71828183,  2.71828183]])

In [73]:
c = (a + b)**2 
c

array([[ 4.,  4.,  4.,  4.],
       [ 4.,  4.,  4.,  4.],
       [ 4.,  4.,  4.,  4.]])

In [74]:
np.sqrt(c)

array([[ 2.,  2.,  2.,  2.],
       [ 2.,  2.,  2.,  2.],
       [ 2.,  2.,  2.,  2.]])

In [77]:
np.sin(c)
np.cos(c)
np.log(c)

array([[ 1.38629436,  1.38629436,  1.38629436,  1.38629436],
       [ 1.38629436,  1.38629436,  1.38629436,  1.38629436],
       [ 1.38629436,  1.38629436,  1.38629436,  1.38629436]])

In [104]:
e = np.eye(5, dtype = int)
e

array([[1, 0, 0, 0, 0],
       [0, 1, 0, 0, 0],
       [0, 0, 1, 0, 0],
       [0, 0, 0, 1, 0],
       [0, 0, 0, 0, 1]])

In [105]:
ran = np.random.randint(1, 10, size = (10,5))
ran

array([[7, 3, 5, 7, 4],
       [4, 2, 5, 1, 5],
       [2, 4, 8, 1, 8],
       [1, 2, 1, 2, 2],
       [5, 7, 5, 1, 3],
       [1, 7, 1, 9, 1],
       [1, 7, 4, 6, 9],
       [7, 6, 1, 2, 9],
       [7, 7, 4, 8, 5],
       [1, 2, 9, 6, 8]])

In [106]:
ran.dot(e)

array([[7, 3, 5, 7, 4],
       [4, 2, 5, 1, 5],
       [2, 4, 8, 1, 8],
       [1, 2, 1, 2, 2],
       [5, 7, 5, 1, 3],
       [1, 7, 1, 9, 1],
       [1, 7, 4, 6, 9],
       [7, 6, 1, 2, 9],
       [7, 7, 4, 8, 5],
       [1, 2, 9, 6, 8]])

### comparison is also elementwise

In [109]:
a = np.random.randint(1, 10, size = (5,5))
a

array([[3, 1, 3, 3, 2],
       [3, 3, 1, 9, 3],
       [7, 6, 9, 9, 1],
       [5, 9, 1, 5, 1],
       [3, 7, 9, 7, 4]])

In [111]:
b = np.random.randint(1, 10, size = (5,5))
b

array([[9, 6, 8, 5, 6],
       [6, 4, 7, 3, 2],
       [1, 4, 7, 7, 2],
       [4, 4, 7, 9, 1],
       [1, 9, 2, 5, 2]])

In [112]:
a == b

array([[False, False, False, False, False],
       [False, False, False, False, False],
       [False, False, False, False, False],
       [False, False, False, False,  True],
       [False, False, False, False, False]], dtype=bool)

In [113]:
a > b

array([[False, False, False, False, False],
       [False, False, False,  True,  True],
       [ True,  True,  True,  True, False],
       [ True,  True, False, False, False],
       [ True, False,  True,  True,  True]], dtype=bool)

### agregate functions

In [114]:
a

array([[3, 1, 3, 3, 2],
       [3, 3, 1, 9, 3],
       [7, 6, 9, 9, 1],
       [5, 9, 1, 5, 1],
       [3, 7, 9, 7, 4]])

In [115]:
a.sum() # sum of all integers

114

In [120]:
a.max() # maximum value of all integers
a.min() # minimum value of all integers

1

In [122]:
a.max(axis = 0) # column wise

array([7, 9, 9, 9, 4])

In [123]:
a.max(axis = 1) # row wise

array([3, 9, 9, 9, 9])

In [124]:
a

array([[3, 1, 3, 3, 2],
       [3, 3, 1, 9, 3],
       [7, 6, 9, 9, 1],
       [5, 9, 1, 5, 1],
       [3, 7, 9, 7, 4]])

In [126]:
a.cumsum(axis = 1)

array([[ 3,  4,  7, 10, 12],
       [ 3,  6,  7, 16, 19],
       [ 7, 13, 22, 31, 32],
       [ 5, 14, 15, 20, 21],
       [ 3, 10, 19, 26, 30]])

In [127]:
a.cumsum(axis = 0)

array([[ 3,  1,  3,  3,  2],
       [ 6,  4,  4, 12,  5],
       [13, 10, 13, 21,  6],
       [18, 19, 14, 26,  7],
       [21, 26, 23, 33, 11]])

In [129]:
a.mean()

4.5599999999999996

In [130]:
a.mean(axis = 0)

array([ 4.2,  5.2,  4.6,  6.6,  2.2])

In [131]:
a.mean(axis = 1)

array([ 2.4,  3.8,  6.4,  4.2,  6. ])

In [164]:
a = np.random.randint(1, 10, 10)
a

array([9, 1, 9, 9, 6, 6, 3, 3, 3, 2])

In [165]:
np.corrcoef(a,a) # correlation matrix

array([[ 1.,  1.],
       [ 1.,  1.]])

In [166]:
np.var(a)

8.6900000000000013

In [167]:
np.std(a) ** 2

8.6899999999999995

In [168]:
a

array([9, 1, 9, 9, 6, 6, 3, 3, 3, 2])

In [169]:
copy = a.copy() # Very important the copy here is deep copy

In [171]:
a[1] = 1000

In [172]:
a

array([   9, 1000,    9,    9,    6,    6,    3,    3,    3,    2])

In [173]:
copy

array([9, 1, 9, 9, 6, 6, 3, 3, 3, 2])

In [174]:
val = 1

In [176]:
from copy import deepcopy

In [177]:
copyVal = deepcopy(val)

In [179]:
val = 100

In [180]:
copyVal

1

In [181]:
a 

array([   9, 1000,    9,    9,    6,    6,    3,    3,    3,    2])

In [182]:
aCopy = deepcopy(a)

In [183]:
a[1] = 999

In [184]:
a

array([  9, 999,   9,   9,   6,   6,   3,   3,   3,   2])

In [185]:
aCopy

array([   9, 1000,    9,    9,    6,    6,    3,    3,    3,    2])

In [ ]:
### copy module is a very important module, because sometimes
### what we really need is deepcopy

### sort arrays

In [252]:
a = np.random.randint(1, 10, (3,4))
a

array([[6, 2, 1, 2],
       [4, 1, 8, 8],
       [5, 3, 6, 9]])

In [251]:
a.sort(axis = 0)
a

array([[4, 4, 5, 1],
       [7, 5, 6, 4],
       [9, 7, 8, 8]])

In [253]:
### how about a desending order sort ???
a

array([[6, 2, 1, 2],
       [4, 1, 8, 8],
       [5, 3, 6, 9]])

In [258]:
a = -a
a.sort(axis = 0)
a = -a

In [260]:
### a brilliant way to do a sorting in a descending order in 
### numpy is: -(-a).sort() since there is no reverse option in
### a.sort()

### subsetting, slicing, indexing

In [261]:
a = np.random.randint(1, 10, (6,8))

In [262]:
a

array([[5, 5, 3, 6, 3, 6, 6, 3],
       [7, 5, 4, 4, 1, 2, 5, 9],
       [7, 3, 3, 4, 3, 1, 5, 8],
       [6, 5, 4, 5, 5, 2, 7, 3],
       [5, 7, 6, 6, 9, 2, 4, 9],
       [6, 5, 6, 2, 3, 2, 7, 3]])

In [265]:
a[1,1] # subsetting

5

In [270]:
a[1,1] # this syntax is very much like the one in matlab

5

In [268]:
a[:5,:5] # slicing

array([[5, 5, 3, 6, 3],
       [7, 5, 4, 4, 1],
       [7, 3, 3, 4, 3],
       [6, 5, 4, 5, 5],
       [5, 7, 6, 6, 9]])

In [274]:
a[0]

array([5, 5, 3, 6, 3, 6, 6, 3])

In [287]:
a[0][::3] # the last element specified the interval length

array([5, 6, 6])

In [291]:
# reverse of the list, the value of the last element can be 
# less than -1
a[0][::-1]

array([3, 6, 6, 3, 6, 3, 5, 5])

In [299]:
a[[0,1,2,3,4,5],[0,1,2,3,4,5]] == a.diagonal()

array([ True,  True,  True,  True,  True,  True], dtype=bool)

In [304]:
a

array([[5, 5, 3, 6, 3, 6, 6, 3],
       [7, 5, 4, 4, 1, 2, 5, 9],
       [7, 3, 3, 4, 3, 1, 5, 8],
       [6, 5, 4, 5, 5, 2, 7, 3],
       [5, 7, 6, 6, 9, 2, 4, 9],
       [6, 5, 6, 2, 3, 2, 7, 3]])

In [309]:
### very import boolean indexing
a[a > 8] # all element larger than 9

array([9, 9, 9])

### array manipulation (matrix manipulation)

In [311]:
a = np.random.randint(1, 10, (3,4))

In [316]:
a

array([[5, 9, 5, 7],
       [9, 8, 4, 9],
       [5, 4, 3, 7]])

In [317]:
a.T

array([[5, 9, 5],
       [9, 8, 4],
       [5, 4, 3],
       [7, 9, 7]])

In [324]:
a.ravel() # flatten the array

array([5, 9, 5, 7, 9, 8, 4, 9, 5, 4, 3, 7])

In [325]:
a

array([[5, 9, 5, 7],
       [9, 8, 4, 9],
       [5, 4, 3, 7]])

In [342]:
b = a.ravel()
b

array([5, 9, 5, 7, 9, 8, 4, 9, 5, 4, 3, 7])

In [343]:
len(b)

12

In [344]:
b.reshape(4, len(b)//4)

array([[5, 9, 5],
       [7, 9, 8],
       [4, 9, 5],
       [4, 3, 7]])

In [345]:
b

array([5, 9, 5, 7, 9, 8, 4, 9, 5, 4, 3, 7])

In [350]:
b.resize((3,4))
b

array([[5, 9, 5, 7],
       [9, 8, 4, 9],
       [5, 4, 3, 7]])

In [351]:
np.append(b,b)

array([5, 9, 5, 7, 9, 8, 4, 9, 5, 4, 3, 7, 5, 9, 5, 7, 9, 8, 4, 9, 5, 4, 3,
       7])

In [355]:
b = b.ravel()
b

array([5, 9, 5, 7, 9, 8, 4, 9, 5, 4, 3, 7])

In [357]:
np.insert(b, 0, 100)

array([100,   5,   9,   5,   7,   9,   8,   4,   9,   5,   4,   3,   7])

In [361]:
b

array([5, 9, 5, 7, 9, 8, 4, 9, 5, 4, 3, 7])

In [362]:
np.delete(b,0)

array([9, 5, 7, 9, 8, 4, 9, 5, 4, 3, 7])

In [363]:
np.delete(b, [0,2,3])

array([9, 9, 8, 4, 9, 5, 4, 3, 7])

In [365]:
### combining arrays
b

array([5, 9, 5, 7, 9, 8, 4, 9, 5, 4, 3, 7])

In [382]:
b = b.reshape((3,4))
b

array([[5, 9, 5, 7],
       [9, 8, 4, 9],
       [5, 4, 3, 7]])

In [369]:
np.concatenate((b,b), axis = 0)

array([[5, 9, 5, 7],
       [9, 8, 4, 9],
       [5, 4, 3, 7],
       [5, 9, 5, 7],
       [9, 8, 4, 9],
       [5, 4, 3, 7]])

In [370]:
np.concatenate((b,b), axis = 1)

array([[5, 9, 5, 7, 5, 9, 5, 7],
       [9, 8, 4, 9, 9, 8, 4, 9],
       [5, 4, 3, 7, 5, 4, 3, 7]])

In [398]:
b = b.ravel()
b = b.reshape((1,len(b)))
b

array([[5, 9, 5, 7, 9, 8, 4, 9, 5, 4, 3, 7]])

In [399]:
b.T

array([[5],
       [9],
       [5],
       [7],
       [9],
       [8],
       [4],
       [9],
       [5],
       [4],
       [3],
       [7]])

In [403]:
np.concatenate((b.T,b.T), axis = 1)

array([[5, 5],
       [9, 9],
       [5, 5],
       [7, 7],
       [9, 9],
       [8, 8],
       [4, 4],
       [9, 9],
       [5, 5],
       [4, 4],
       [3, 3],
       [7, 7]])

In [407]:
b = b.ravel()
b

array([5, 9, 5, 7, 9, 8, 4, 9, 5, 4, 3, 7])

In [409]:
np.column_stack((b,b))

array([[5, 5],
       [9, 9],
       [5, 5],
       [7, 7],
       [9, 9],
       [8, 8],
       [4, 4],
       [9, 9],
       [5, 5],
       [4, 4],
       [3, 3],
       [7, 7]])

In [429]:
b = b.reshape(3,4)
print(b)

[[5 9 5 7]
 [9 8 4 9]
 [5 4 3 7]]


### split the matrix

In [436]:
m = np.random.randint(1, 10, (6,8))
m

array([[2, 2, 4, 9, 2, 1, 7, 4],
       [1, 3, 2, 8, 4, 6, 9, 4],
       [1, 3, 5, 4, 1, 4, 1, 3],
       [5, 3, 1, 4, 6, 2, 3, 8],
       [9, 8, 6, 2, 4, 2, 4, 3],
       [9, 3, 4, 6, 4, 2, 4, 5]])

In [441]:
# h stands for horizontally 
for i in np.hsplit(m,4):
    print(i)
    print()

[[2 2]
 [1 3]
 [1 3]
 [5 3]
 [9 8]
 [9 3]]

[[4 9]
 [2 8]
 [5 4]
 [1 4]
 [6 2]
 [4 6]]

[[2 1]
 [4 6]
 [1 4]
 [6 2]
 [4 2]
 [4 2]]

[[7 4]
 [9 4]
 [1 3]
 [3 8]
 [4 3]
 [4 5]]



In [446]:
for i in np.vsplit(m,3):
    print(i)
    print()

[[2 2 4 9 2 1 7 4]
 [1 3 2 8 4 6 9 4]]

[[1 3 5 4 1 4 1 3]
 [5 3 1 4 6 2 3 8]]

[[9 8 6 2 4 2 4 3]
 [9 3 4 6 4 2 4 5]]

